import { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";

const PageHome: FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Daniel Robles Garcia es UN PENDEJO PELON!!
        </h1>
      </main>
    </div>
  );
};

export default PageHome;
